## Input directives
participants_tsv: participants.tsv

MSTRCHT:
  bids: /project/6007967/rhaast/10_ZonaIncerta/bids
  mp2rage_correction: /scratch/rhaast/B1corr/data/mp2rage_correction
  uni_orig: _acq-UNI_run-01_MP2RAGE.nii.gz
  uni_corr: _acq-UNI_run-01_proc-SA2RAGE_MP2RAGE.nii.gz
  uni_den: _acq-MP2RAGEpostproc_run-01_T1w.nii.gz
  t1_orig: _acq-MP2RAGE_run-01_T1map.nii.gz
  t1_corr: _acq-MP2RAGE_run-01_proc-SA2RAGE_T1map.nii.gz
  inv1: _inv-1_run-01_MP2RAGE.nii.gz
  inv2: _inv-2_run-01_MP2RAGE.nii.gz
  b1: _acq-MP2RAGE_run-01_proc-SA2RAGE_B1map.nii.gz
SNSX:
  bids: /project/6007967/rhaast/02_SNSX_7T/cfmm-bids
  mp2rage_correction: /project/6007967/rhaast/02_SNSX_7T/derivatives/mp2ragecorrection
  uni_orig: _acq-UNI_run-01_MP2RAGE.nii.gz
  uni_corr: _acq-UNI_run-01_MP2RAGE_B1corr.nii.gz
  uni_den: _acq-MP2RAGE_run-01_T1w.nii.gz  
  t1_orig: _acq-MP2RAGE_run-01_T1map.nii.gz
  t1_corr: _acq-MP2RAGE_run-01_T1map_B1corr.nii.gz
  inv1: _inv-1_run-01_MP2RAGE.nii.gz
  inv2: _inv-2_run-01_MP2RAGE.nii.gz
  b1: _acq-b1map_SA2RAGE_s3mm_B1corr.nii.gz


## Freesurfer
fs_license: /project/6007967/akhanf/opt/freesurfer/.license
subjects_dir: 'output/freesurfer_spm'
modalities:
  - uni
  - t1
  - thickness
timepoints:
  - orig
  - corr
hemispheres:
  - lh
  - rh


## Surfmorph
surfmorph_script: /scratch/rhaast/surfmorph/run.sh
nr_iterations: 4
rois:
  hippocampus: [17, 53]


## Singularity
standard: /project/6007967/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif
tar2bids: /project/6007967/akhanf/singularity/bids-apps/khanlab_tar2bids_v0.0.5e.sif
surfmorph: /project/6007967/akhanf/singularity/bids-apps/khanlab_surfmorph_latest.sif #/scratch/rhaast/singularity/surfmorph.simg
nighres: /scratch/rhaast/singularity/nighres.simg
